### ISSUE TITLE
assimp543 migration bot error due to missing v6.12 branch

### ISSUE THREAD

**Issue by traversaro** [conda-forge/dartsim-feedstock#97]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The https://conda-forge.org/status/migration/?name=assimp543 bot is failing on dartsim (job: https://github.com/regro/cf-scripts/actions/runs/11046563216) with error:

~~~
bot error (
[bot CI job](https://github.com/regro/cf-scripts/actions/runs/11046563216)
): v6.12:
Traceback (most recent call last):
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 163, in _run_git_command
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'checkout', '--quiet', '--track', 'upstream/v6.12']' returned non-zero exit status 128.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 407, in clone_fork_and_branch
    self.checkout_branch(target_dir, f"upstream/{base_branch}", track=True)
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 308, in checkout_branch
    self._run_git_command(
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 167, in _run_git_command
    raise GitCliError("Error running git command.") from e
conda_forge_tick.git_utils.GitCliError: Error running git command.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 163, in _run_git_command
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'checkout', '--quiet', '-b', 'v6.12', 'upstream/v6.12']' returned non-zero exit status 128.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 721, in _run_migrator_on_feedstock_branch
    migrator_uid, pr_json = run_with_tmpdir(
                            ^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 445, in run_with_tmpdir
    return run(
           ^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 502, in run
    if not _prepare_feedstock_repository(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 184, in _prepare_feedstock_repository
    backend.clone_fork_and_branch(
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 519, in clone_fork_and_branch
    self.cli.clone_fork_and_branch(
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 415, in clone_fork_and_branch
    self.checkout_new_branch(
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 326, in checkout_new_branch
    self._run_git_command(
  File "/home/runner/micromamba/envs/cf-scripts/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/git_utils.py", line 167, in _run_git_command
    raise GitCliError("Error running git command.") from e
conda_forge_tick.git_utils.GitCliError: Error running git command.
~~~

I guess that the problem is that `v6.12` is listed as an `abi_migration_branches` in https://github.com/conda-forge/dartsim-feedstock/blob/4cd834c8e38effb12471779caee338f169277e46/conda-forge.yml#L1-L3, but the branch was not present anymore? 

Just to clarify why I added back in time the `v6.12` branch, was to have ABI migration also on the 6.12, as it is the version used in Gazebo Fortress that we would like to support at least for some time. If you prefer to avoid having the `v6.12` branch, probably we need to remove it from `abi_migration_branches` .

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by traversaro** [comment]
I guess the latest commit of the `v6.12` branch was https://github.com/conda-forge/dartsim-feedstock/commit/cf5ffe5dcee5cd92ed8d290c6f8355f9f26f6f0b, at least that was the one used for the last 6.12.* build: https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Fdartsim-6.12.2-ha2fd85f_12.conda .

**Comment by jslee02** [comment]
I'm a bit confused. Do you mean the v6.12 branch in this repo (dartsim-feedstock)? In any case, please go ahead with whatever makes sense for the automation. I'm still learning the conda-forge ecosystem.

**Comment by traversaro** [comment]
> I'm a bit confused. Do you mean the v6.12 branch in this repo (dartsim-feedstock)?

Yes, the `v6.12` branch used by `abi_migration_branches` in this repo, it is used to build 6.12 binaries with updated dependencies (mostly assimp). I will try to restore it, thanks!

**Comment by traversaro** [comment]
Cool, I was not aware restoring branches was easy as going in https://github.com/conda-forge/dartsim-feedstock/activity?activity_type=branch_deletion !

**Comment by traversaro** [comment]
The branch is now available again at https://github.com/conda-forge/dartsim-feedstock/tree/v6.12 .

**Comment by jslee02** [comment]
Oh, I accidentally deleted the branch. Sorry about that! Thanks for fixing it!
